# file: logwatch/tasks/main.yml

- name: Logwatch | Make sure logwatch and its dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - logwatch
    - libdate-manip-perl
